import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { build } from "../scripts/build.mjs";

const fixture = new URL("./fixtures/catalog.snapshot.json", import.meta.url);
test("bad input preserves prior generated bytes", () => {
  const output = mkdtempSync(join(tmpdir(), "qs-nav-"));
  const readme = join(output, "README.md"); writeFileSync(readme, "prior");
  assert.throws(() => build(join(output, "missing.json"), output));
  assert.equal(readFileSync(readme, "utf8"), "prior");
});

test("mixed duplicate unknown and missing declarations preserve prior bytes", () => {
  const base = JSON.parse(readFileSync(fixture, "utf8"));
  for (const mutate of [
    (value) => value.assets.push(structuredClone(value.assets[0])),
    (value) => value.assets[0].catalog.category = "99",
    (value) => delete value.assets[0].summary_en,
  ]) {
    const output = mkdtempSync(join(tmpdir(), "qs-nav-")); const target = join(output, "snapshot.json"); const prior = join(output, "README.md");
    const value = structuredClone(base); mutate(value); writeFileSync(target, JSON.stringify(value)); writeFileSync(prior, "prior");
    assert.throws(() => build(target, output)); assert.equal(readFileSync(prior, "utf8"), "prior");
  }
});
