import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { build } from "../scripts/build.mjs";
import { buildCatalogModel } from "../scripts/catalog-model.mjs";
import { renderReadme } from "../scripts/render-readme.mjs";
import { renderSiteData } from "../scripts/render-site-data.mjs";
import { verifyBuild } from "../scripts/verify-build.mjs";

const fixture = new URL("./fixtures/catalog.snapshot.json", import.meta.url);
test("bad input preserves prior generated bytes", () => {
  const output = mkdtempSync(join(tmpdir(), "qs-nav-"));
  const readme = join(output, "README.md"); writeFileSync(readme, "prior");
  assert.throws(() => build(join(output, "missing.json"), output));
  assert.equal(readFileSync(readme, "utf8"), "prior");
});

test("mixed duplicate unknown and missing declarations preserve prior bytes", () => {
  const base = JSON.parse(readFileSync(fixture, "utf8"));
  for (const mutate of [
    (value) => value.assets.push(structuredClone(value.assets[0])),
    (value) => value.assets[0].catalog.category = "99",
    (value) => delete value.assets[0].summary_en,
  ]) {
    const output = mkdtempSync(join(tmpdir(), "qs-nav-")); const target = join(output, "snapshot.json"); const prior = join(output, "README.md");
    const value = structuredClone(base); mutate(value); writeFileSync(target, JSON.stringify(value)); writeFileSync(prior, "prior");
    assert.throws(() => build(target, output)); assert.equal(readFileSync(prior, "utf8"), "prior");
  }
});

test("verification rejects coordinated README URL and summary tampering", () => {
  const snapshot = JSON.parse(readFileSync(fixture, "utf8"));
  const model = buildCatalogModel(snapshot);
  const site = { ...renderSiteData(model), profiles: snapshot.profiles.items, adapters: snapshot.adapters.items, compatibility_edges: snapshot.compatibility_edges };
  const output = mkdtempSync(join(tmpdir(), "qs-nav-verify-"));
  try {
    const asset = snapshot.assets[0];
    const tamper = (text) => text.replaceAll(asset.url, "https://example.invalid/forged").replaceAll(asset.summary_zh, "forged zh summary").replaceAll(asset.summary_en, "forged en summary");
    writeFileSync(join(output, "README.md"), tamper(renderReadme(model, "zh")));
    writeFileSync(join(output, "README.en.md"), tamper(renderReadme(model, "en")));
    const siteDirectory = join(output, "site");
    mkdirSync(siteDirectory, { recursive: true });
    writeFileSync(join(siteDirectory, "catalog.json"), `${JSON.stringify(site, null, 2)}\n`);
    assert.throws(() => verifyBuild(output, snapshot), /README|projection|output/i);
  } finally {
    rmSync(output, { recursive: true, force: true });
  }
});
